name: Tests

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: yarn install

      - name: Run algorithms tests
        run: yarn test:algo

      - name: Run data structures tests
        run: yarn test:ds
